name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the form below to help us understand your request.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm the following
      options:
        - label: I have searched existing issues and discussions for similar feature requests
          required: true
        - label: I have read the documentation to ensure this isn't already possible
          required: true

  - type: dropdown
    id: type
    attributes:
      label: Feature Type
      options:
        - New generator option
        - New decorator support
        - New output format
        - Performance improvement
        - Developer experience
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem are you trying to solve?
      placeholder: |
        I'm always frustrated when...
        Currently, I have to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this to work?
      placeholder: |
        I would like to be able to...
        The generator should...
    validations:
      required: true

  - type: textarea
    id: schema-example
    attributes:
      label: Schema Example
      description: Show how this would look in a Prisma schema (if applicable)
      render: prisma
      placeholder: |
        generator nestgraphql {
          provider     = "nestjs-prisma-graphql"
          newOption    = true
        }

        model User {
          /// @NewDecorator()
          id String @id
        }
    validations:
      required: false

  - type: textarea
    id: output-example
    attributes:
      label: Expected Output
      description: What should the generated code look like?
      render: typescript
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternatives or workarounds?
    validations:
      required: false

  - type: dropdown
    id: willingness
    attributes:
      label: Contribution
      description: Would you be willing to help implement this feature?
      options:
        - "Yes, I can submit a PR"
        - "Yes, with guidance"
        - "No, but I can help test"
        - "No"
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or examples
    validations:
      required: false
